language: ruby
rvm:
  - 2.2.2
bundler_args: --without development staging production assets

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database store_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake

cache:
  bundler: true
  directories:
    - tmp/assets/cache/test/sprockets

