SECRET_TOKEN:
DEVISE_SECRET:
DEFAULT_EMAIL_FROM:               test@test.com
DOMAIN_NAME:                      store.dev
ADMIN_EMAIL:                      test@test.com
ADMIN_PASSWORD:                   12345678
ADMIN_NAME:                       test_admin
#store information
STORE_NAME:                       The Flower Alley
STORE_URL:                        thefloweralley.com
STORE_STATE:                      Michigan
DEFAULT_SEO_TITLE:                The Flower Alley
DEFAULT_SEO_DESCRIPTION:          Novis Best Florist
DEFAULT_EMAIL_FROM:               noreply@thefloweralley.com

production:
  SECRET_TOKEN:
  DEVISE_SECRET:
  DOMAIN_NAME:                    store.herokuapp.com
  RACK_ENV:                       production
  RAILS_ENV:                      production
  EMAIL_USERNAME:                 test@test.com
  EMAIL_PASSWORD:                 123456789
